import type { CheerioAPI } from "cheerio";
import type { AnyNode } from "domhandler";
import type { Locator } from "playwright-core";
import { detectFormPlugins, type FormPluginFingerprint } from "@/lib/audit/detectors/form-plugins";
import { makeFinding, type AuditModule, type Finding } from "@/lib/audit/types";

const MAX_FORMS_TO_TEST = 2;
const MAX_LISTED_ITEMS = 10;

const NAME_TEXT = "QA Audit Test";
const EMAIL_TEXT = "qa-audit-test@example.com";
const PHONE_TEXT = "0000000000";
const MESSAGE_TEXT =
  "This is an automated QA audit test submission generated by the WordPress AI QA Auditor. Please disregard this entry.";

const EXCLUDED_FIELD_TYPES = new Set(["hidden", "submit", "button", "image", "file", "reset"]);

interface TestPlanEntry {
  label: string;
  locatorSelector: string;
  nth: number;
  successSelector: string;
  errorSelector: string;
  isUnknown: boolean;
}

function attr($: CheerioAPI, el: AnyNode, name: string): string {
  return ($(el).attr(name) ?? "").trim();
}

function fieldTypeOf($: CheerioAPI, el: AnyNode): string {
  const tag = "tagName" in el ? String((el as { tagName?: string }).tagName ?? "").toLowerCase() : "";
  if (tag === "select") return "select";
  if (tag === "textarea") return "textarea";
  const type = attr($, el, "type").toLowerCase();
  return type || "text";
}

function isVisibleFormField($: CheerioAPI, el: AnyNode): boolean {
  const type = fieldTypeOf($, el);
  return !EXCLUDED_FIELD_TYPES.has(type);
}

function hasRequiredMarkup($: CheerioAPI, el: AnyNode): boolean {
  const $el = $(el);
  return $el.attr("required") !== undefined || $el.attr("aria-required")?.toLowerCase() === "true";
}

function fieldHaystack($: CheerioAPI, el: AnyNode): string {
  return `${attr($, el, "name")} ${attr($, el, "id")} ${attr($, el, "placeholder")}`.toLowerCase();
}

function isEmailField($: CheerioAPI, el: AnyNode): boolean {
  return fieldTypeOf($, el) === "email" || fieldHaystack($, el).includes("email");
}

function isPhoneField($: CheerioAPI, el: AnyNode): boolean {
  const type = fieldTypeOf($, el);
  const haystack = fieldHaystack($, el);
  return type === "tel" || haystack.includes("phone") || haystack.includes("tel");
}

function emailValidatedProperly($: CheerioAPI, el: AnyNode): boolean {
  return fieldTypeOf($, el) === "email" || $(el).attr("pattern") !== undefined;
}

function phoneValidatedProperly($: CheerioAPI, el: AnyNode): boolean {
  return fieldTypeOf($, el) === "tel" || $(el).attr("pattern") !== undefined;
}

function isSearchLikeForm($: CheerioAPI, formEl: AnyNode): boolean {
  const $form = $(formEl);
  if ($form.attr("role")?.toLowerCase() === "search") return true;
  if ($form.find('input[name="s"]').length > 0) return true;
  const id = $form.attr("id") ?? "";
  const cls = $form.attr("class") ?? "";
  return id === "searchform" || /\bsearch-form\b/.test(cls);
}

function describeForm($: CheerioAPI, formEl: AnyNode): string {
  const $form = $(formEl);
  const id = $form.attr("id");
  const cls = $form.attr("class");
  if (id) return `#${id}`;
  if (cls) return `.${cls.split(/\s+/)[0]}`;
  return "<form>";
}

export const formsModule: AuditModule = {
  category: "forms",
  label: "Forms",
  run: async (ctx) => {
    const findings: Finding[] = [];
    const { $, url, html } = ctx;

    const allFormEls = $("form").toArray();

    if (allFormEls.length === 0) {
      findings.push(
        makeFinding({
          category: "forms",
          title: "No forms found on the page",
          status: "pass",
          severity: "info",
          pageUrl: url,
          description: "No <form> elements were found on this page, so no form testing was applicable.",
          whyItMatters: "This is informational; not every page is expected to contain a form.",
          recommendation: "No action needed.",
          estimatedFixTime: "0 minutes",
        }),
      );
      return findings;
    }

    const matchedPlugins: FormPluginFingerprint[] = detectFormPlugins(html);

    // ---------------------------------------------------------------------
    // Static validation-markup checks — run across every form on the page.
    // ---------------------------------------------------------------------
    const fieldSelector = "input, textarea, select";

    const formsMissingRequiredMarkup: string[] = [];
    const emailFieldChecks: { form: string; ok: boolean }[] = [];
    const phoneFieldChecks: { form: string; ok: boolean }[] = [];

    for (const formEl of allFormEls) {
      const $form = $(formEl);
      const fields = $form.find(fieldSelector).toArray().filter((el) => isVisibleFormField($, el));
      const formLabel = describeForm($, formEl);

      const hasAnyRequiredMarkup = fields.some((el) => hasRequiredMarkup($, el));
      if (fields.length > 0 && !hasAnyRequiredMarkup) {
        formsMissingRequiredMarkup.push(formLabel);
      }

      for (const el of fields) {
        if (isEmailField($, el)) {
          emailFieldChecks.push({ form: formLabel, ok: emailValidatedProperly($, el) });
        }
        if (isPhoneField($, el)) {
          phoneFieldChecks.push({ form: formLabel, ok: phoneValidatedProperly($, el) });
        }
      }
    }

    // Required-field markup
    if (formsMissingRequiredMarkup.length === 0) {
      findings.push(
        makeFinding({
          category: "forms",
          title: "Forms mark required fields appropriately",
          status: "pass",
          severity: "info",
          pageUrl: url,
          description: `All ${allFormEls.length} form${allFormEls.length === 1 ? "" : "s"} detected on this page have at least one field marked with the required attribute or aria-required.`,
          whyItMatters: "Marking required fields lets browsers and assistive technology provide native validation feedback to visitors before submission.",
          recommendation: "No action needed.",
          estimatedFixTime: "0 minutes",
        }),
      );
    } else {
      findings.push(
        makeFinding({
          category: "forms",
          title: "Forms without required-field markup",
          status: "fail",
          severity: "medium",
          pageUrl: url,
          description: `${formsMissingRequiredMarkup.length} of ${allFormEls.length} form(s) have no fields marked with the required attribute or aria-required="true": ${formsMissingRequiredMarkup.slice(0, MAX_LISTED_ITEMS).join(", ")}.`,
          whyItMatters: "Without required-field markup, browsers and screen readers cannot warn visitors before they submit an incomplete form, leading to confusing server-side errors instead.",
          recommendation: "Add the required attribute (and/or aria-required=\"true\") to fields that must be filled in before submission.",
          estimatedFixTime: "20 minutes",
          meta: { forms: formsMissingRequiredMarkup.slice(0, MAX_LISTED_ITEMS) },
        }),
      );
    }

    // Email field validation markup
    if (emailFieldChecks.length > 0) {
      const badEmailFields = emailFieldChecks.filter((f) => !f.ok);
      if (badEmailFields.length === 0) {
        findings.push(
          makeFinding({
            category: "forms",
            title: "Email fields use proper validation markup",
            status: "pass",
            severity: "info",
            pageUrl: url,
            description: `All ${emailFieldChecks.length} detected email field(s) use type="email" or a validation pattern attribute.`,
            whyItMatters: "type=\"email\" gives visitors instant, native format validation and brings up the correct keyboard on mobile devices.",
            recommendation: "No action needed.",
            estimatedFixTime: "0 minutes",
          }),
        );
      } else {
        findings.push(
          makeFinding({
            category: "forms",
            title: "Email fields missing proper validation markup",
            status: "fail",
            severity: "medium",
            pageUrl: url,
            description: `${badEmailFields.length} of ${emailFieldChecks.length} detected email field(s) are not using type="email" or a pattern attribute: ${badEmailFields.slice(0, MAX_LISTED_ITEMS).map((f) => f.form).join(", ")}.`,
            whyItMatters: "Without type=\"email\", visitors lose native format validation and mobile devices won't show an email-optimized keyboard.",
            recommendation: 'Change the input type to type="email" (or add a suitable pattern attribute).',
            estimatedFixTime: "10 minutes",
            meta: { forms: badEmailFields.slice(0, MAX_LISTED_ITEMS).map((f) => f.form) },
          }),
        );
      }
    }

    // Phone field validation markup
    if (phoneFieldChecks.length > 0) {
      const badPhoneFields = phoneFieldChecks.filter((f) => !f.ok);
      if (badPhoneFields.length === 0) {
        findings.push(
          makeFinding({
            category: "forms",
            title: "Phone fields use sensible validation markup",
            status: "pass",
            severity: "info",
            pageUrl: url,
            description: `All ${phoneFieldChecks.length} detected phone field(s) use type="tel" or a validation pattern attribute.`,
            whyItMatters: "type=\"tel\" brings up a phone-optimized keyboard on mobile and signals intent for validation/formatting.",
            recommendation: "No action needed.",
            estimatedFixTime: "0 minutes",
          }),
        );
      } else {
        findings.push(
          makeFinding({
            category: "forms",
            title: "Phone fields missing sensible validation markup",
            status: "fail",
            severity: "low",
            pageUrl: url,
            description: `${badPhoneFields.length} of ${phoneFieldChecks.length} detected phone field(s) are not using type="tel" or a pattern attribute: ${badPhoneFields.slice(0, MAX_LISTED_ITEMS).map((f) => f.form).join(", ")}.`,
            whyItMatters: "Without type=\"tel\", mobile visitors don't get the numeric keypad, and there is no baseline format hint.",
            recommendation: 'Change the input type to type="tel" (optionally with a pattern attribute for stricter formatting).',
            estimatedFixTime: "10 minutes",
            meta: { forms: badPhoneFields.slice(0, MAX_LISTED_ITEMS).map((f) => f.form) },
          }),
        );
      }
    }

    // ---------------------------------------------------------------------
    // Build the live-submission test plan (first N testable forms).
    // ---------------------------------------------------------------------
    const perPluginCounter = new Map<string, number>();
    const testPlan: TestPlanEntry[] = [];

    allFormEls.forEach((formEl, globalIndex) => {
      if (isSearchLikeForm($, formEl)) return;

      const $form = $(formEl);
      const matchedFp = matchedPlugins.find((fp) => {
        try {
          return $form.is(fp.formSelector);
        } catch {
          return false;
        }
      });

      if (matchedFp) {
        const count = perPluginCounter.get(matchedFp.slug) ?? 0;
        perPluginCounter.set(matchedFp.slug, count + 1);
        testPlan.push({
          label: matchedFp.name,
          locatorSelector: matchedFp.formSelector,
          nth: count,
          successSelector: matchedFp.successSelector,
          errorSelector: matchedFp.errorSelector,
          isUnknown: false,
        });
        return;
      }

      const hasVisibleSubmit =
        $form.find('button[type="submit"], input[type="submit"]').length > 0 ||
        $form.find("button").filter((_, b) => attr($, b, "type") === "").length > 0;

      if (!hasVisibleSubmit) return;

      testPlan.push({
        label: "Unknown/custom form",
        locatorSelector: "form",
        nth: globalIndex,
        successSelector: "",
        errorSelector: "",
        isUnknown: true,
      });
    });

    const plannedForTesting = testPlan.slice(0, MAX_FORMS_TO_TEST);

    if (testPlan.length > MAX_FORMS_TO_TEST) {
      findings.push(
        makeFinding({
          category: "forms",
          title: "Only the first forms on the page were live-tested",
          status: "pass",
          severity: "info",
          pageUrl: url,
          description: `${testPlan.length} testable forms were found on this page; only the first ${MAX_FORMS_TO_TEST} were submitted live to limit noise/risk. The rest were still covered by the static validation-markup checks above.`,
          whyItMatters: "Limiting live submissions avoids generating excessive test entries/emails while still covering markup-level checks for every form.",
          recommendation: "If desired, manually test the remaining forms.",
          estimatedFixTime: "0 minutes",
        }),
      );
    }

    // ---------------------------------------------------------------------
    // Live submission testing.
    // ---------------------------------------------------------------------
    for (let i = 0; i < plannedForTesting.length; i++) {
      const plan = plannedForTesting[i];
      try {
        const formLocator = ctx.page.locator(plan.locatorSelector).nth(plan.nth);
        await formLocator.waitFor({ state: "visible", timeout: 5000 });

        const fieldLocators = await formLocator.locator("input, textarea, select").all();
        let lastFillable: Locator | null = null;

        for (const field of fieldLocators) {
          const tagName = await field.evaluate((el) => el.tagName.toLowerCase()).catch(() => "input");
          const rawType = (await field.getAttribute("type").catch(() => null))?.toLowerCase() ?? "";
          const type = rawType || (tagName === "input" ? "text" : tagName);

          if (EXCLUDED_FIELD_TYPES.has(type)) continue;

          const isVisible = await field.isVisible().catch(() => false);
          if (!isVisible) continue;

          const name = (await field.getAttribute("name").catch(() => null)) ?? "";
          const id = (await field.getAttribute("id").catch(() => null)) ?? "";
          const placeholder = (await field.getAttribute("placeholder").catch(() => null)) ?? "";
          const haystack = `${name} ${id} ${placeholder}`.toLowerCase();

          if (tagName === "select") {
            const options = await field.locator("option").all();
            for (const opt of options) {
              const val = await opt.getAttribute("value").catch(() => null);
              if (val && val.trim() !== "") {
                await field.selectOption(val).catch(() => undefined);
                break;
              }
            }
            continue;
          }

          if (type === "checkbox") {
            const required = await field.getAttribute("required").catch(() => null);
            const ariaRequired = await field.getAttribute("aria-required").catch(() => null);
            if (required !== null || ariaRequired?.toLowerCase() === "true") {
              await field.check().catch(() => undefined);
            }
            continue;
          }

          if (type === "radio") {
            // Skip radio groups: correctness of "which option" can't be inferred safely.
            continue;
          }

          if (tagName === "textarea" || haystack.includes("message") || haystack.includes("comment")) {
            await field.fill(MESSAGE_TEXT).catch(() => undefined);
            lastFillable = field;
            continue;
          }

          if (type === "email" || haystack.includes("email")) {
            await field.fill(EMAIL_TEXT).catch(() => undefined);
            lastFillable = field;
            continue;
          }

          if (type === "tel" || haystack.includes("phone") || haystack.includes("tel")) {
            await field.fill(PHONE_TEXT).catch(() => undefined);
            lastFillable = field;
            continue;
          }

          if (type === "text" || type === "" || tagName === "input") {
            await field.fill(NAME_TEXT).catch(() => undefined);
            lastFillable = field;
          }
        }

        const submitButton = formLocator.locator('button[type="submit"], input[type="submit"]').first();
        const submitCount = await submitButton.count().catch(() => 0);
        if (submitCount > 0) {
          await submitButton.click();
        } else if (lastFillable) {
          await lastFillable.press("Enter").catch(() => undefined);
        }

        await Promise.race([
          plan.successSelector
            ? ctx.page.waitForSelector(plan.successSelector, { timeout: 6000 }).catch(() => null)
            : Promise.resolve(null),
          plan.errorSelector
            ? ctx.page.waitForSelector(plan.errorSelector, { timeout: 6000 }).catch(() => null)
            : Promise.resolve(null),
          ctx.page.waitForTimeout(2500),
        ]);

        let successVisible = false;
        let errorVisible = false;
        let errorText = "";

        if (plan.successSelector) {
          successVisible = await ctx.page.locator(plan.successSelector).first().isVisible().catch(() => false);
        }
        if (plan.errorSelector) {
          const errLoc = ctx.page.locator(plan.errorSelector).first();
          errorVisible = await errLoc.isVisible().catch(() => false);
          if (errorVisible) {
            errorText = ((await errLoc.textContent().catch(() => null)) ?? "").trim();
          }
        }

        if (successVisible) {
          findings.push(
            makeFinding({
              category: "forms",
              title: `Form submission succeeded: ${plan.label} (form ${i + 1})`,
              status: "pass",
              severity: "info",
              pageUrl: url,
              description: `Submitted a test entry to form ${i + 1} (${plan.label}) with placeholder QA test data, and a success confirmation message appeared.`,
              whyItMatters: "Confirms visitors submitting this form receive clear feedback that their submission went through.",
              recommendation: "No action needed. A test entry was submitted with obviously fake data (e.g. \"QA Audit Test\") — it can be safely deleted/ignored.",
              estimatedFixTime: "0 minutes",
              meta: { plugin: plan.label, formIndex: i + 1 },
            }),
          );
        } else if (errorVisible) {
          findings.push(
            makeFinding({
              category: "forms",
              title: `Form submission returned an error: ${plan.label} (form ${i + 1})`,
              status: "fail",
              severity: "medium",
              pageUrl: url,
              description: `Submitting form ${i + 1} (${plan.label}) with test data produced a validation/error message${errorText ? `: "${errorText}"` : "."}`,
              whyItMatters: "If a correctly filled-out form still triggers a validation error, real visitors may be unable to successfully submit the form.",
              recommendation: "Review the form's validation rules and confirm real visitor input can be submitted successfully.",
              estimatedFixTime: "30 minutes",
              meta: { plugin: plan.label, formIndex: i + 1, errorText },
            }),
          );
        } else {
          findings.push(
            makeFinding({
              category: "forms",
              title: `Form submission outcome could not be confirmed: ${plan.label} (form ${i + 1})`,
              status: "warning",
              severity: "low",
              pageUrl: url,
              description: `Test data was submitted to form ${i + 1} (${plan.label}), but neither a success nor error indicator could be confirmed within the wait window. The form may redirect to a thank-you page or use an AJAX message this scan's fixed selectors don't recognize.`,
              whyItMatters: "Without a confirmed outcome, it's unknown whether this form is actually working for real visitors.",
              recommendation: "Manually submit this form and confirm it produces the expected confirmation.",
              estimatedFixTime: "10 minutes",
              meta: { plugin: plan.label, formIndex: i + 1 },
            }),
          );
        }
      } catch (err) {
        findings.push(
          makeFinding({
            category: "forms",
            title: `Form could not be tested live: ${plan.label} (form ${i + 1})`,
            status: "warning",
            severity: "low",
            pageUrl: url,
            description: `An error occurred while attempting to fill and submit form ${i + 1} (${plan.label}): ${err instanceof Error ? err.message : String(err)}`,
            whyItMatters: "Without a completed live test, it's unknown whether this form works correctly for visitors.",
            recommendation: "Manually test this form's submission flow.",
            estimatedFixTime: "10 minutes",
            meta: { plugin: plan.label, formIndex: i + 1 },
          }),
        );
      }
    }

    if (testPlan.length === 0) {
      findings.push(
        makeFinding({
          category: "forms",
          title: "No testable forms found for live submission",
          status: "pass",
          severity: "info",
          pageUrl: url,
          description: "Form elements were present on the page, but none had a recognizable submit control (or all were search forms already covered by the Search module), so no live submission test was performed.",
          whyItMatters: "This is informational; static validation-markup checks above still apply.",
          recommendation: "No action needed.",
          estimatedFixTime: "0 minutes",
        }),
      );
    }

    return findings;
  },
};
